/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#006875",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#90CAF9",
        "on-background": "#ffffff",
        "inverse-primary": "#2D68D0",
        "on-tertiary-fixed": "#0A3260",
        "secondary-dim": "#00d4ec",
        "error": "#ff6e84",
        "surface": "#0e0e0e",
        "tertiary-dim": "#42A5F5",
        "primary-container": "#7AA8F5",
        "inverse-on-surface": "#565555",
        "primary": "#5B8CE8",
        "on-secondary-fixed-variant": "#005964",
        "background": "#0e0e0e",
        "on-tertiary": "#0D3B6E",
        "tertiary-fixed-dim": "#64B5F6",
        "surface-tint": "#5B8CE8",
        "on-surface-variant": "#adaaaa",
        "primary-fixed-dim": "#6499F2",
        "on-error": "#490013",
        "on-secondary-container": "#e8fbff",
        "on-error-container": "#ffb2b9",
        "surface-variant": "#262626",
        "tertiary": "#64B5F6",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed": "#003a42",
        "surface-dim": "#0e0e0e",
        "surface-container": "#1a1a1a",
        "error-dim": "#d73357",
        "outline": "#767575",
        "error-container": "#a70138",
        "surface-container-highest": "#262626",
        "on-primary-fixed-variant": "#002080",
        "surface-container-high": "#20201f",
        "on-tertiary-fixed-variant": "#1565C0",
        "on-primary": "#001A5E",
        "outline-variant": "#484847",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#90CAF9",
        "secondary": "#00e3fd",
        "on-surface": "#ffffff",
        "primary-dim": "#3268D6",
        "on-primary-container": "#001040",
        "surface-container-low": "#131313",
        "secondary-fixed": "#26e6ff",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary": "#004d57",
        "on-tertiary-container": "#072952",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#7AA8F5",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
